### ISSUE TITLE
There is no Registration things

### ISSUE THREAD

**Issue by MuhammadShakkeer2030** [voidChetan/hotel_booking_angular#1]
![image](https://github.com/voidChetan/hotel_booking_angular/assets/121001685/7ddb7185-5763-47ba-a26a-278a8356bd58)

**Comment by Krystofe** [comment]
hello, 

it's not possible to test the project ?

**Comment by MuhammadShakkeer2030** [comment]
> Refere

**Comment by MuhammadShakkeer2030** [comment]
> hello,
> 
> it's not possible to test the project ?

my question is how to login this project
